POSSystem/Models/ProductView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POSSystem.Models
{
    public class ProductView
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
    }
    public class SalesProductView
    {
        public int ID { get; set; }
        public string Name{ get; set; }
        public Double Price { get; set; }
        public int Quantity { get; set; }
        public Double Total { get; set; }
        public int AvailableQuantity { get; set; }
        public string Image { get; set; }
        public string Category { get; set; }
    }
}

POSSystem/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using POSSystem.DAL.Repository;
using POSSystem.Models;
using static POSSystem.DAL.Repository.ProductRepository;

namespace POSSystem.Controllers
{
    public class ProductController : Controller
    {
        public ProductRepository productRepository = new ProductRepository();
        // GET: Product
        [Authorize]
        public async Task<ActionResult> Index()
        {
            IndexView indexView = new IndexView()
            {
                ProductsList = await GetConsolidatedProductList(),
                Sale = new SaleView()
            };
            return View(indexView);
        }
        public ActionResult AddProductToSale(int id)
        {
            List<SalesProductView> salesProducts = Session["ProductSaleList"] as List<SalesProductView>;
            var _saleProduct = salesProducts.Where(s => s.ID == id).FirstOrDefault();
            _saleProduct.AvailableQuantity -= 1;
            _saleProduct.Quantity += 1;
            _saleProduct.Total = _saleProduct.Quantity * _saleProduct.Price;
            Session["ProductSaleList"] = salesProducts;
            IndexView viewModel = new IndexView()
            {
                ProductsList = salesProducts,
                Sale = new SaleView()
            };
            return PartialView("_Page", viewModel);
        }
        public ActionResult DecrementQuantity(int id)
        {
            List<SalesProductView> salesProducts = Session["ProductSaleList"] as List<SalesProductView>;
            var _saleProduct = salesProducts.Where(s => s.ID == id).FirstOrDefault();
            _saleProduct.Quantity -= 1;
            _saleProduct.AvailableQuantity += 1;
            if (_saleProduct.Quantity == 0)
            {
                salesProducts.Remove(_saleProduct);
            }
            else
            {
                _saleProduct.Total = _saleProduct.Quantity * _saleProduct.Price;
            }
            Session["ProductSaleList"] = salesProducts;
            IndexView viewModel = new IndexView()
            {
                ProductsList = salesProducts,
                Sale = new SaleView()
            };
            return PartialView("_Page", viewModel);
        }
        public async Task<ActionResult> CancelSale()
        {
            IndexView viewModel = new IndexView()
            {
                ProductsList = await GetConsolidatedProductList(),
                Sale = new SaleView()
            };
            return PartialView("_Page", viewModel);
        }

        [NonAction]
        public async Task<List<SalesProductView>> GetConsolidatedProductList()
        {
            var productList = await productRepository.GetProductList();
            var products = new List<ProductView>();
            Session["ProductSaleList"] = new List<SalesProductView>();

            foreach (var product in productList)
            {
                (Session["ProductSaleList"] as List<SalesProductView>).Add(new SalesProductView()
                {
                    ID = product.ID,
                    AvailableQuantity = product.AvailableQuantity,
                    Name = product.Name,
                    Price = product.UnitPrice,
                    Quantity = 0,
                    Total = 0,
                    Image = product.Image,
                    Category = product.Category
                });
            }
            return Session["ProductSaleList"] as List<SalesProductView>;
        }
    }
}

POSSystem/Controllers/SaleController.cs
using POSSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POSSystem.DAL.Repository;
using POSSystem.DAL.Models;
using System.Threading.Tasks;

namespace POSSystem.Controllers
{
    public class SaleController : Controller
    {
        [HttpPost]
        public async Task<ActionResult> AddSale(SaleView saleView)
        {
            SaleRepository saleRepository = new SaleRepository();
            ProductRepository productRepository = new ProductRepository();

            Sale sale = new Sale()
            {
                CreatedOn = DateTime.Now,
                EmployeeUsername = User.Identity.Name,
                TotalPrice = saleView.Total,
                VAT = saleView.VAT,
                Products = new List<Product>()
            };
            List<SalesProductView> salesProducts = Session["ProductSaleList"] as List<SalesProductView>;
            salesProducts = salesProducts.Where(x => x.Quantity != 0).ToList();
            foreach (var product in salesProducts)
            {
                Product _product = new Product()
                {
                    ID = product.ID,
                    Name = product.Name,
                    UnitPrice = product.Price,
                    Category = product.Category,
                    AvailableQuantity = product.AvailableQuantity,
                    Image = product.Image
                };
                await productRepository.UpdateSaleForProduct(_product);
                sale.Products.Add(_product);
            }
            if (ModelState.IsValid)
            {
                var result = await saleRepository.AddSale(sale);
                return RedirectToAction("GetReciept", result);
            }
            else
            {
                return Json(false);
            }
        }
        public ActionResult GetReciept(Sale sale)
        {
            SaleView saleView = new SaleView()
            {
                CreatedOn = sale.CreatedOn,
                InvoiceNumber = sale.InvoiceNumber,
                Total = sale.TotalPrice,
                VAT = sale.VAT
            };
            return PartialView("_ProcessSale", saleView);
        }
    }
}

POSSystem/Views/Product/Index.cshtml
@model POSSystem.Models.IndexView
@{
    ViewBag.Title = "POS System";
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/Content/bootstrap.css" />

<div class="row" id="page">
    @Html.Partial("_Page", Model)
</div>

<div id="process-sale-dialog" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    &times;
                </button>
                <h4 class="modal-title">
                </h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>
<div id="cancel-sale-dialog" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    &times;
                </button>
                <h4 class="modal-title">
                </h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" onclick="cancelSale()">Yes</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">
                    No
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    function openDialog() {
        $("#cancel-sale-dialog .modal-body").html("<p>Are you Sure?</p>");
        $("#cancel-sale-dialog").modal("show");
    }
    function addProductInSale(id) {
        $.ajax({
            url: "@Url.Action("AddProductToSale", "Product", new {id = "-1" })".replace("-1", id),
            method: "GET",
            contentType:'text/html',
            success: function (data) {
                    $("#page").html(data);
                    console.log("success");
                    updateCosts();
                }
            });
    }
    function removeProductInSale(id) {
        $.ajax({
            url: "@Url.Action("DecrementQuantity", "Product", new {id = "-1" })".replace("-1", id),
            method: "GET",
            contentType:'text/html',
            success: function (data) {
                $("#page").html(data);
                console.log("success");
                updateCosts();
                }
            });
    }
    function cancelSale() {
        $.ajax({
            url: "@Url.Action("CancelSale", "Product")",
            method: "GET",
            contentType:'text/html',
            success: function (data) {
                $("#page").html(data);
                $("#cancel-sale-dialog").modal("hide");
                $("#process-sale-dialog .modal-body").html("<p>Sale is Cancelled!</p>");
                $("#process-sale-dialog").modal("show");               
                $("#SubTotal").val('0');
                $("#Total").val('0');
                }
            });
    }
    function clearSale() {
        $.ajax({
            url: "@Url.Action("CancelSale", "Product")",
            method: "GET",
            contentType:'text/html',
            success: function (data) {
                $("#page").html(data);
                $("#SubTotal").val('0');
                $("#Total").val('0');
                }
            });
    }
    function updateCosts() {
        var subTotal = 0;
        $(".total-cost").each(function () {
            subTotal = parseFloat(subTotal) + parseFloat($(this).val());
        });
        if ($("#Discount").val()) {
            subTotal = parseFloat(subTotal) - 0.01 * parseFloat($("#Discount").val()) * parseFloat(subTotal);
        }
        $("#SubTotal").val(subTotal);
        $("#Total").val(parseFloat(subTotal) + parseFloat($("#VAT").val() ? $("#VAT").val() : '0'));
    }
    function processSale() {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("AddSale", "Sale")',
            data: {
                'VAT': $("#VAT").val(),
                'Discount': $("#Discount").val(),
                'SubTotal': $("#SubTotal").val(),
                'Total': $("#Total").val()
            },
            success: function(data){
                console.log('success!');
                $("#process-sale-dialog .modal-body").html(data);
                $("#process-sale-dialog .modal-body").find(".minus-quatity").remove();
                $("#process-sale-dialog .modal-body").find(".plus-quatity").remove();
                $("#process-sale-dialog").modal("show");
                clearSale();
                $("#SubTotal").val('0');
                $("#Total").val('0');
            }
});
    }
</script>

POSSystem/Views/Product/_ProductList.cshtml
@model IEnumerable<POSSystem.Models.SalesProductView>
    <div>
        @foreach (var item in Model)
        {
            if (item.AvailableQuantity != 0)
            {
            <div id="product_@item.ID" style="float:left;width:20%;height:80px;margin:5px;background-image:url('../../Content/images/@item.Image');">
                @item.Name
                <button type="button" class="add_to_sale" id="@item.ID" onclick="addProductInSale(@item.ID)">Add</button>
            </div>
            }
        }
    </div>